---
kind: pipeline
type: docker
name: main

platform:
  os: linux
  arch: amd64

node:
  type: benchmark

steps:
  - name: Restore cache
    image: appleboy/drone-sftp-cache
    settings:
      server:
        from_secret: sftp-cache-host
      port:
        from_secret: sftp-cache-port
      username:
        from_secret: sftp-cache-user
      password:
        from_secret: sftp-cache-password
      path: milib
      restore: true
      mount:
        - blast
        - src/test/resources/big

  - name: Initialize environment for tests
    image: buildpack-deps:18.04-curl
    commands:
      - ./init.sh

  - name: Rebuild cache
    image: appleboy/drone-sftp-cache
    settings:
      server:
        from_secret: sftp-cache-host
      port:
        from_secret: sftp-cache-port
      username:
        from_secret: sftp-cache-user
      password:
        from_secret: sftp-cache-password
      path: milib
      rebuild: true
      mount:
        - blast
        - src/test/resources/big

---

kind: pipeline
type: docker
name: status_reporting

platform:
  os: linux
  arch: amd64

depends_on:
  - main

trigger:
  status:
    - success
    - failure

steps:
  - name: Send Telegram Notification
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: telegram-token
      to:
        from_secret: telegram-chat-id-micore

---
kind: signature
hmac: 27b9d3f435c11864d26b259d4b40e0110e9f5b38dd62de06e53a39372806297d

...
