---
kind: pipeline
type: docker
name: main

platform:
  os: linux
  arch: amd64

node:
  type: benchmark

steps:
  - name: Restore cache
    image: appleboy/drone-sftp-cache
    settings:
      server:
        from_secret: sftp-cache-host
      port:
        from_secret: sftp-cache-port
      username:
        from_secret: sftp-cache-user
      password:
        from_secret: sftp-cache-password
      path: /home
      restore: true
      mount:
        - blast
        - src/test/resources/big

  - name: Initialize environment for tests
    image: buildpack-deps:18.04-curl
    commands:
      - export
      - ./init.sh
      - ./init.benchmark.sh
    secrets:
      - source: sftp-data-host
        target: test_secret

  - name: Benchmarks with JDK 8
    image: maven:3-jdk-8
    commands:
      - ./run.benchmarks.sh

  - name: Rebuild cache
    image: appleboy/drone-sftp-cache
    settings:
      server:
        from_secret: sftp-cache-host
      port:
        from_secret: sftp-cache-port
      username:
        from_secret: sftp-cache-user
      password:
        from_secret: sftp-cache-password
      path: /home
      rebuild: true
      mount:
        - blast
        - src/test/resources/big

---

kind: pipeline
type: docker
name: status_reporting

platform:
  os: linux
  arch: amd64

depends_on:
  - main

trigger:
  status:
    - success
    - failure

steps:
  - name: Send Telegram Notification
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: telegram-token
      to:
        from_secret: telegram-chat-id-micore

---
kind: signature
hmac: 267a902d5aab1cec0bf7679dc762d66a67429d46a9a5aa403d3ba7ee13333632

...
